name: DEPLOY PROD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: DEPLOY PROD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: docker login -u danilocassola -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t danilocassola/fiap-lanchonete:v2 .
          docker push danilocassola/fiap-lanchonete:v2
